In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df=pd.read_csv("C:/Users/soori/Desktop/face class/Data sci-Projects/project 3/Iris (1).csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
x=df.iloc[:,[1,2,3,4]].values
x[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [5]:
y=df.iloc[:,-1]
y[:5]

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
y[:5]

array([0, 0, 0, 0, 0])

In [12]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [14]:
x_train[:5]

array([[ 0.01543995, -0.11925475,  0.22512685,  0.35638175],
       [-0.09984503, -1.04039491,  0.11355956, -0.02864805],
       [ 1.05300481, -0.11925475,  0.95031423,  1.12644135],
       [-1.36797986,  0.34131533, -1.39259884, -1.31208072],
       [ 1.1682898 ,  0.11103029,  0.72717965,  1.38312788]])

In [15]:
x_test[:5]

array([[-0.09984503, -0.57982483,  0.72717965,  1.51147115],
       [ 0.13072494, -1.96153508,  0.11355956, -0.28533458],
       [-0.44569998,  2.64416573, -1.33681519, -1.31208072],
       [ 1.62942973, -0.34953979,  1.39658338,  0.74141155],
       [-1.0221249 ,  0.80188541, -1.28103155, -1.31208072]])

In [16]:
from sklearn.svm import SVC

In [17]:
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(x_train, y_train)

SVC(random_state=0)

In [18]:
y_pred = classifier.predict(x_test)

In [19]:
classifier.score(x_test, y_test)

0.9736842105263158